# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11UtSTwAkgpED934Mid2KS1_tnPkZuLB0
"""

## punto 3 de la evaluacion.
import time

class Fibonacci:
    def __init__(self, num_final):
        self.num_final = num_final
        self.num1=0
        self.num2 =1

    def __iter__(self):
        return self

    def __next__(self):
        if self.num1 > self.num_final:
            raise StopIteration
        resultado = self.num1
        self.num1, self.num2 = self.num2, self.num1 + self.num2
        return resultado

if __name__ == "__main__":
    num = int(input("Ingrese el número final de Fibonacci: "))

    fibonacci_secuencia = Fibonacci(num)

    for numero in fibonacci_secuencia:
        print(numero)
        time.sleep(5)