FROM python:latest

LABEL Maintainer="gsampallo"

WORKDIR /usr/app/src

COPY *.py ./
COPY requirements.txt ./
COPY test.jpg ./
RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./test.py"]